### ISSUE TITLE
Add GitHub Actions workflow for automated release creation on PR merge

### ISSUE THREAD

**Issue by moshe5745** [moshe5745/localpost#9]
**Feature Request**: Implement a GitHub Actions workflow to automate the creation of releases for `localpost` whenever a pull request (PR) is merged into the `main` branch. This will build binaries for supported platforms (Linux and macOS, with Windows to be added later) and attach them to a GitHub release, simplifying distribution and enabling contributors to focus on features without manual release steps.

**Context**:
`localpost` is a CLI tool for testing HTTP requests using YAML configurations. Currently, releases (e.g., binaries for distribution) are created manually, which requires repository write access and adds overhead. Automating releases via GitHub Actions will:
- Build binaries for Linux and macOS (and prepare for Windows in a follow-up issue).
- Create a GitHub release with attached binaries when a PR is merged.
- Streamline contributions by removing manual release tasks.
This is a beginner-friendly task, ideal for those new to GitHub Actions or open-source, as it involves setting up a straightforward CI pipeline with Go.

**Why**:
- Automation reduces manual work—faster, consistent releases.
- Enables contributors without write access to trigger releases via PRs.
- Prepares for cross-platform support (e.g., Windows binary in future issues).
- Improves user experience—binaries readily available in releases.

**Proposed Implementation**:
- [ ] **Create GitHub Actions Workflow**:
  - Add a `.github/workflows/release.yml` file.
  - Trigger on `pull_request` merge to `main` or on `push` to `main` with a new tag (e.g., `v*`).
  - Build binaries for Linux (`GOOS=linux GOARCH=amd64`) and macOS (`GOOS=darwin GOARCH=amd64`).
  - Use `actions/create-release` and `actions/upload-release-asset` to create a release and attach binaries.
- [ ] **Test Workflow**:
  - Verify workflow runs on PR merge or tag push.
  - Check binaries in release assets (e.g., `localpost-linux-amd64`, `localpost-darwin-amd64`).
  - Test binaries locally (e.g., run `localpost --version` on Linux/macOS).
- [ ] **Update Documentation**:
  - Add release process details to `CONTRIBUTING.md` or `README.md`.
  - Explain how contributors trigger releases via PRs (e.g., “Merge a PR with a `v1.0.1` tag”).
- [ ] **Prepare for Windows**:
  - Add a placeholder in the workflow for Windows (`GOOS=windows GOARCH=amd64`)—commented out for now.
  - Note that Windows binary will be enabled in a follow-up issue.

**Example Workflow** (Draft):
```yaml
name: Create Release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - name: Build Linux Binary
        run: GOOS=linux GOARCH=amd64 go build -o localpost-linux-amd64
      - name: Build macOS Binary
        run: GOOS=darwin GOARCH=amd64 go build -o localpost-darwin-amd64
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: true
          prerelease: false
      - name: Upload Linux Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./localpost-linux-amd64
          asset_name: localpost-linux-amd64
          asset_content_type: application/octet-stream
      - name: Upload macOS Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./localpost-darwin-amd64
          asset_name: localpost-darwin-amd64
          asset_content_type: application/octet-stream
```
